### PR TITLE
RFC: systemd: introduce sway-session{,-pre}.target

### LINKED ISSUE #4: Should there be a `sway-session.target`

### PR DESCRIPTION
**Pull request by xdbob**
Closes: #4

### CODE REVIEW

**Comment by xdbob** [comment]
It seams to be racy. I must investigate.

On occasion, at least `swayidle.service` starts before sway has imported the environment

**Comment by xdbob** [comment]
@gdamjan I know It's been a few months but I think I fixed my race. Could you test this branch ?

**Comment by gdamjan** [comment]
give me a day or two :)

**Comment by gdamjan** [comment]
seems fine.

I must say `sway-user-service` is quite involved, and haven't tested it.

ps. I know see the arch package includes some files but they seem buggy, I guess it'll need some bug reporting
https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/sway

**Pull request merged**
